/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.hdsb.gwss.jmaie.u5;

import java.util.Calendar;

/**
 *
 * @author 1yijam
 */
public class AgeCheckerGUI extends javax.swing.JFrame {

    /**
     * Creates new form AgeCheckerGUI
     */
    public AgeCheckerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orangePanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        month = new javax.swing.JLabel();
        monthSelect = new javax.swing.JComboBox<>();
        day = new javax.swing.JLabel();
        daySelect = new javax.swing.JSpinner();
        year = new javax.swing.JLabel();
        yearSelect = new javax.swing.JTextField();
        button = new javax.swing.JButton();
        result = new javax.swing.JLabel();
        birthdayResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        orangePanel.setBackground(new java.awt.Color(255, 153, 51));
        orangePanel.setForeground(new java.awt.Color(255, 153, 51));

        title.setFont(new java.awt.Font("Rockwell", 0, 36)); // NOI18N
        title.setText("Age Checker");

        month.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        month.setText("Month");

        monthSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        monthSelect.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        monthSelect.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        monthSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthSelectActionPerformed(evt);
            }
        });

        day.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        day.setText("Day");

        daySelect.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        daySelect.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        year.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        year.setText("Year");

        yearSelect.setText("enter year");
        yearSelect.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        yearSelect.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                yearSelectFocusGained(evt);
            }
        });
        yearSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearSelectActionPerformed(evt);
            }
        });

        button.setBackground(new java.awt.Color(102, 255, 102));
        button.setText("Press Me");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        birthdayResult.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout orangePanelLayout = new javax.swing.GroupLayout(orangePanel);
        orangePanel.setLayout(orangePanelLayout);
        orangePanelLayout.setHorizontalGroup(
            orangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orangePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(orangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(orangePanelLayout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, orangePanelLayout.createSequentialGroup()
                        .addComponent(month)
                        .addGap(18, 18, 18)
                        .addComponent(monthSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(daySelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(year)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yearSelect, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orangePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(birthdayResult)
                .addGap(110, 110, 110))
            .addGroup(orangePanelLayout.createSequentialGroup()
                .addGroup(orangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orangePanelLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(button))
                    .addGroup(orangePanelLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(result)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        orangePanelLayout.setVerticalGroup(
            orangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orangePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(birthdayResult)
                .addGap(18, 18, 18)
                .addComponent(title)
                .addGap(49, 49, 49)
                .addGroup(orangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daySelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(result)
                .addGap(18, 18, 18)
                .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orangePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orangePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monthSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthSelectActionPerformed
        System.out.println("MONTH CHANGED, CHANGE DAYS");
    }//GEN-LAST:event_monthSelectActionPerformed

    private void yearSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearSelectActionPerformed
        System.out.println("YEAR CHANGED, CHANGE DAYS");

    }//GEN-LAST:event_yearSelectActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        Calendar c = Calendar.getInstance();
        int month = c.get(Calendar.MONTH)-1;
        int day = c.get(Calendar.DAY_OF_MONTH);
        int year = c.get(Calendar.YEAR);  // TODO add your handling code here:
        int inputYear = Integer.parseInt(yearSelect.getText().trim());
        int inputMonth = monthSelect.getSelectedIndex();
        int inputDay = (int) daySelect.getValue();
        int yearDiff = year - inputYear;
        int monthDiff = month - inputMonth;
        int dayDiff = day - inputDay;
        if (yearDiff < 16) {
            result.setText("You are younger than 16(year)");
       } else if (yearDiff > 16){
            result.setText("You are older than 16(year)");
       } else {
            if (monthDiff < 0) {
                result.setText("You are younger than 16(month)");
            } else if (monthDiff > 0) {
                result.setText("You are older than 16(month)");
            } else {
                if (dayDiff < 0){
                    result.setText("You are younger than 16(day)");
                } else {
                    result.setText("You are older than 16(day)"); 
                }
            }
                
            }
        if (monthDiff == 0 && dayDiff == 0){
            birthdayResult.setText("Happy Birthday!");
        }
        
        
    }//GEN-LAST:event_buttonActionPerformed

    private void yearSelectFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yearSelectFocusGained
        // TODO add your handling code here:
        yearSelect.setText("");
    }//GEN-LAST:event_yearSelectFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgeCheckerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgeCheckerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgeCheckerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgeCheckerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgeCheckerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birthdayResult;
    private javax.swing.JButton button;
    private javax.swing.JLabel day;
    private javax.swing.JSpinner daySelect;
    private javax.swing.JLabel month;
    private javax.swing.JComboBox<String> monthSelect;
    private javax.swing.JPanel orangePanel;
    private javax.swing.JLabel result;
    private javax.swing.JLabel title;
    private javax.swing.JLabel year;
    private javax.swing.JTextField yearSelect;
    // End of variables declaration//GEN-END:variables
}
